DROP TABLE IF EXISTS BACKUP_BANK_BRANCH;
CREATE TABLE BACKUP_BANK_BRANCH LIKE BANK_BRANCH;
INSERT INTO BACKUP_BANK_BRANCH SELECT * FROM BANK_BRANCH;

DROP TABLE IF EXISTS BACKUP_CARRIES;
CREATE TABLE BACKUP_CARRIES LIKE CARRIES;
INSERT INTO BACKUP_CARRIES SELECT * FROM CARRIES;

DROP TABLE IF EXISTS BACKUP_COMPLAINT;
CREATE TABLE BACKUP_COMPLAINT LIKE COMPLAINT;
INSERT INTO BACKUP_COMPLAINT SELECT * FROM COMPLAINT;

DROP TABLE IF EXISTS BACKUP_CUSTOMER;
CREATE TABLE BACKUP_CUSTOMER LIKE CUSTOMER;
INSERT INTO BACKUP_CUSTOMER SELECT * FROM CUSTOMER;

DROP TABLE IF EXISTS BACKUP_CUST_TRANSACTION;
CREATE TABLE BACKUP_CUST_TRANSACTION LIKE CUST_TRANSACTION;
INSERT INTO BACKUP_CUST_TRANSACTION SELECT * FROM CUST_TRANSACTION;

DROP TABLE IF EXISTS BACKUP_EXTERNAL_OFFERS;
CREATE TABLE BACKUP_EXTERNAL_OFFERS LIKE EXTERNAL_OFFERS;
INSERT INTO BACKUP_EXTERNAL_OFFERS SELECT * FROM EXTERNAL_OFFERS;

DROP TABLE IF EXISTS BACKUP_HAS_EXCLUSIVE_RIGHTS;
CREATE TABLE BACKUP_HAS_EXCLUSIVE_RIGHTS LIKE HAS_EXCLUSIVE_RIGHTS;
INSERT INTO BACKUP_HAS_EXCLUSIVE_RIGHTS SELECT * FROM HAS_EXCLUSIVE_RIGHTS;

DROP TABLE IF EXISTS BACKUP_ORDERS;
CREATE TABLE BACKUP_ORDERS LIKE ORDERS;
INSERT INTO BACKUP_ORDERS SELECT * FROM ORDERS;

DROP TABLE IF EXISTS BACKUP_PAYMENT_SCHEDULE;
CREATE TABLE BACKUP_PAYMENT_SCHEDULE LIKE PAYMENT_SCHEDULE;
INSERT INTO BACKUP_PAYMENT_SCHEDULE SELECT * FROM PAYMENT_SCHEDULE;

DROP TABLE IF EXISTS BACKUP_PAYMENT_SOURCE;
CREATE TABLE BACKUP_PAYMENT_SOURCE LIKE PAYMENT_SOURCE;
INSERT INTO BACKUP_PAYMENT_SOURCE SELECT * FROM PAYMENT_SOURCE;

DROP TABLE IF EXISTS BACKUP_PRODUCT;
CREATE TABLE BACKUP_PRODUCTS LIKE PRODUCT;
INSERT INTO BACKUP_PRODUCTS SELECT * FROM PRODUCT;

DROP TABLE IF EXISTS BACKUP_PRODUCT_SUPPLIER;
CREATE TABLE BACKUP_PRODUCT_SUPPLIER LIKE PRODUCT_SUPPLIER;
INSERT INTO BACKUP_PRODUCT_SUPPLIER SELECT * FROM PRODUCT_SUPPLIER;